import { useState, type ReactNode, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { loadManagement, type Snapshot, type ManagedOrder, type ManagedProduct, type Shop } from '../lib/management';
import { demoSave, demoTiers, isDemo, type Collection } from '../lib/demo';
import { useSession } from '../lib/useSession';
import { useAsyncResource, type AsyncResource } from '../lib/useAsyncResource';
import { fcfa, entier, delai, pourcentage, libelleStatut } from '../lib/format';
import { createProduct, replaceTiers } from '../lib/api/endpoints';
import { tierFromApi, toApiTiers, validateTiers, type EditableTier } from '../lib/tiers';
import { TierEditor } from '../components/TierEditor';
import { ShareBox } from '../components/ShareBox';
import { DashboardCharts } from '../components/DashboardCharts';
import { Badge, Confirm, DataTable, Metric, Notice, Panel } from './ManagementUI';
import AssignmentOutlined from '@mui/icons-material/AssignmentOutlined';
import GroupsOutlined from '@mui/icons-material/GroupsOutlined';
import PaymentsOutlined from '@mui/icons-material/PaymentsOutlined';
import ScheduleOutlined from '@mui/icons-material/ScheduleOutlined';
import TrendingDownOutlined from '@mui/icons-material/TrendingDownOutlined';

const titles = { users: 'Utilisateurs', shops: 'Commerçants', products: 'Produits', groups: 'Groupes', orders: 'Commandes' };
const useData = (pollMs = 0) => useAsyncResource(loadManagement, [], {pollMs});
function State({resource, children}: {resource: AsyncResource<Snapshot>; children: (data: Snapshot) => ReactNode}) {
  if (resource.isLoading || !resource.data) return <section className="empty">{resource.error ? <><p role="alert">{resource.error.message}</p><button onClick={resource.refresh}>Réessayer</button></> : <p role="status">Chargement des données…</p>}</section>;
  return <>{resource.error && <p role="alert" className="form-error">Actualisation impossible : {resource.error.message}. Les dernières données restent affichées. <button onClick={resource.refresh}>Réessayer</button></p>}{children(resource.data)}</>;
}
function Heading({title, text, action}: {title: string; text: string; action?: ReactNode}) {return <div className="page-heading"><div><h2 className="page-title">{title}</h2><p className="page-intro">{text}</p></div>{action}</div>;}
function person(data: Snapshot, id: number) {const u = data.users.find(u => u.id === id); return u ? `${u.first_name} ${u.last_name}` : `Acheteur n° ${id}`;}
function product(data: Snapshot, id: number) {return data.products.find(p => p.id === id)?.name ?? `Produit n° ${id}`;}
function groupName(data: Snapshot, id: number) {return data.groups.find(g => g.id === id)?.name ?? `Groupe n° ${id}`;}
function GroupTable({data, activeOnly = false}: {data: Snapshot; activeOnly?: boolean}) {return <DataTable title="Groupes" rows={data.groups.filter(g => !activeOnly || g.status === 'OPEN')} search={g => `${g.name} ${g.product.name}`} filters={[{label: 'Statut', value: g => g.status}]} columns={[
  {label: 'Groupe / produit', render: g => <><Link className="row-title" to={`/groupes/${g.id}`}>{g.name}</Link><small>{g.product.name}</small></>},
  {label: 'Participants', secondary: true, render: g => entier(g.participants_count)},
  {label: 'Unités / objectif', render: g => <><span>{entier(g.current_quantity)} / {entier(g.target_quantity)} {g.product.unit_label}s</span><small className="mobile-group-summary">{entier(g.participants_count)} participants ? {fcfa(g.current_unit_price)}{g.next_tier && <> ? Prochain : {fcfa(g.next_tier.unit_price)}</>}</small><progress aria-label={`Progression de ${g.name}`} max={1} value={g.progress_ratio} /></>},
  {label: 'Prix actuel', align: 'right', secondary: true, render: g => <>{fcfa(g.current_unit_price)}{g.next_tier && <small>Prochain : {fcfa(g.next_tier.unit_price)}</small>}</>},
  {label: 'Échéance', render: g => <><Badge value={g.status} /><small>{delai(g.seconds_remaining)}</small></>},
]} />;}
function OrderTable({data, orders = data.orders, onOpen}: {data: Snapshot; orders?: ManagedOrder[]; onOpen: (id: number) => void}) {return <DataTable title="Commandes" rows={orders} search={o => `${o.id} ${person(data, o.user_id)} ${product(data, o.product_id)} ${groupName(data, o.group_id)}`} filters={[{label:'Commande', value:o => o.order_status}, {label:'Livraison', value:o => o.delivery_status}, {label:'Paiement', value:o => o.payment_status}]} columns={[
  {label:'Commande / acheteur', render: o => <><button className="text-action" onClick={() => onOpen(o.id)}>KF-{o.id}</button><small>{person(data, o.user_id)}</small></>},
  {label:'Produit / groupe', secondary: true, render:o => <>{product(data, o.product_id)}<small>{groupName(data, o.group_id)}</small></>},
  {label:'Unités', secondary: true, render:o => entier(o.quantity)}, {label:'Montant', align:'right', render:o => <>{fcfa(o.total_amount)}<small>{o.quantity} × {fcfa(o.unit_price)}</small></>},
  {label:'Paiement simulé', render:o => <Badge value={o.payment_status} />}, {label:'Livraison', secondary: true, render:o => <Badge value={o.delivery_status} />}
]} />;}
function OrderDetail({data, id, close, refresh}: {data: Snapshot; id:number; close: () => void; refresh: () => void}) {
  const o = data.orders.find(o => o.id === id); const [error, setError] = useState(''); if (!o) return null;
  const next: Record<string, [string, string]> = {NEW: ['CONFIRMED', 'Confirmer la commande'], CONFIRMED: ['PREPARED', 'Marquer comme préparée'], PREPARED: ['SHIPPED', 'Marquer comme expédiée'], SHIPPED: ['DELIVERED', 'Marquer comme livrée']};
  return <Panel title={`Commande KF-${o.id}`} close={close}><dl className="details"><dt>Acheteur</dt><dd>{person(data,o.user_id)}</dd><dt>Groupe</dt><dd><Link to={`/groupes/${o.group_id}`} onClick={close}>{groupName(data,o.group_id)}</Link></dd><dt>Commerçant</dt><dd>{data.shops.find(s => s.id === o.merchant_id)?.name ?? 'Non fourni'}</dd><dt>Produit</dt><dd>{product(data,o.product_id)}</dd><dt>Quantité</dt><dd>{o.quantity} unités</dd><dt>Prix unitaire</dt><dd>{fcfa(o.unit_price)}</dd><dt>Montant total</dt><dd>{fcfa(o.total_amount)}</dd><dt>Commande</dt><dd><Badge value={o.order_status} /></dd><dt>Paiement simulé</dt><dd><Badge value={o.payment_status} /></dd><dt>Référence de transaction</dt><dd>{o.transaction_reference}</dd><dt>Livraison</dt><dd><Badge value={o.delivery_status} /></dd><dt>Date de commande</dt><dd>{new Date(o.created_at).toLocaleString('fr-FR')}</dd></dl><Notice>Chaque paiement appartient à cette commande individuelle. Le créateur du groupe ne reçoit pas l’argent des membres.</Notice>{isDemo() && o.order_status !== 'CANCELLED' && next[o.delivery_status] && <button className="button-primary" onClick={() => {try {const [status] = next[o.delivery_status]; demoSave('orders', o.id, {delivery_status: status, order_status: 'CONFIRMED'}); refresh();} catch(e) {setError((e as Error).message);}}}>{next[o.delivery_status][1]}</button>}{error && <p role="alert">{error}</p>}</Panel>;
}
export function ManagementOverview() {
  const resource = useData(2000); const admin = useSession()?.user.role === 'ADMIN'; const [order, setOrder] = useState<number | null>(null);
  return <State resource={resource}>{data => {const k = data.impact; const m = data.merchant; return <><Heading title={admin ? 'L’activité en un regard' : (m?.business_name || 'Votre activité')} text={admin ? 'Les indicateurs essentiels de la plateforme.' : 'Vos principaux indicateurs commerciaux.'} action={admin ? <button onClick={resource.refresh} disabled={resource.isRefreshing}>Actualiser</button> : <Link className="button button-primary" to="/offres/nouvelle">Créer une offre</Link>} /><div className="metrics metrics-overview">{admin && k ? <><Metric icon={<TrendingDownOutlined />} label="Économies générées" value={fcfa(k.community_savings)} note="Hors annulations" description="Écart cumulé entre les prix individuels et les prix groupés des commandes non annulées." /><Metric icon={<PaymentsOutlined />} label="Valeur commandée" value={fcfa(k.total_order_value)} description="Valeur cumulée des commandes non annulées, avec paiements simulés dans le MVP." /><Metric icon={<GroupsOutlined />} label="Groupes actifs" value={entier(k.groups_active)} description="Nombre de groupes actuellement ouverts et accessibles aux acheteurs." /><Metric icon={<AssignmentOutlined />} label="Commandes" value={entier(k.orders)} description="Nombre total de commandes enregistrées sur la plateforme." /></> : <><Metric icon={<PaymentsOutlined />} label="CA simulé" value={fcfa(m?.revenue_simule ?? 0)} note="Hors annulations" /><Metric icon={<AssignmentOutlined />} label="Commandes" value={entier(m?.orders ?? 0)} /><Metric icon={<ScheduleOutlined />} label="En attente" value={entier(m?.pending_orders ?? 0)} /><Metric icon={<GroupsOutlined />} label="Groupes actifs" value={data.groups.filter(g => g.status === 'OPEN').length} /></>}</div>
  {admin && <DashboardCharts data={data} />}
  <section className="activity-summary" aria-labelledby="activity-summary-title">
    <h2 id="activity-summary-title">Statistiques de l’activité</h2>
    <dl className="activity-grid">
      {(admin && k ? [
        ['Utilisateurs inscrits', entier(k.users)],
        [isDemo() ? 'Comptes activés' : 'Utilisateurs actifs', data.activity ? entier(data.activity.enabled_users) : 'Indisponible'],
        ['Commerçants', entier(k.merchants)],
        ['Produits actifs', entier(k.products)],
        ['Groupes créés', entier(k.groups_created)],
        ['Groupes réussis', entier(k.groups_successful)],
        ['Groupes terminés', data.activity ? entier(data.activity.completed_groups) : 'Indisponible'],
        ['Groupes ouverts hors délai', data.activity ? entier(data.activity.overdue_open_groups) : 'Indisponible'],
        ['Taux de réussite', pourcentage(k.success_rate) + ' %'],
      ] : [
        ['Unités commandées', entier(m?.units ?? 0)],
        ['Produits actifs', entier(data.products.filter(p => p.status === 'ACTIVE').length)],
      ]).map(([label, value]) => <div className="activity-stat" key={label}><dt>{label}</dt><dd className={value === 'Indisponible' ? 'value-unavailable' : ''}>{value}</dd></div>)}
    </dl>
    {admin && <details className="definitions"><summary>Comment sont calculés ces indicateurs ?</summary>
      <p>Les économies correspondent aux commandes non annulées, y compris celles des groupes ouverts. Le taux de réussite rapporte les groupes ? objectif atteint ou terminés ? tous les groupes créés.</p>
      <p>{isDemo() ? 'Dans cette démonstration, les comptes activés sont les comptes dont le statut est actif ; cela ne mesure pas une activité récente. Les groupes ouverts hors délai sont ceux dont la date limite est dépassée.' : 'L’API ne fournit pas encore le nombre d’utilisateurs actifs, de groupes terminés ni de groupes ouverts hors délai. Ces valeurs restent indiquées comme indisponibles plutôt que remplacées par zéro.'}</p>
    </details>}
  </section>
  {admin && data.shops.some(s => s.status === 'PENDING') && <div className="attention"><div><strong>{data.shops.filter(s => s.status === 'PENDING').length} boutique à valider</strong><small>Vérifiez ses informations avant de l’accepter.</small></div><Link to="/commercants">Examiner les boutiques</Link></div>}
  <div className="section-heading-row"><h2>Groupes actifs</h2>{admin && <Link to="/groupes">Tous les groupes</Link>}</div><GroupTable data={data} activeOnly /><div className="section-heading-row"><h2>Dernières commandes</h2><Link to="/commandes">Toutes les commandes</Link></div>{data.missing.includes('orders') ? <Notice>La liste des commandes professionnelles n’est pas encore fournie par l’API. Les totaux ci-dessus proviennent des agrégats existants.</Notice> : <OrderTable data={data} orders={[...data.orders].sort((a,b) => b.created_at.localeCompare(a.created_at)).slice(0,5)} onOpen={setOrder} />}{order !== null && <OrderDetail data={data} id={order} close={() => setOrder(null)} refresh={resource.refresh} />}</>;}}</State>;
}

export function ManagementPage({kind, offers = false}: {kind: Collection; offers?: boolean}) {
  const resource = useData(); const admin = useSession()?.user.role === 'ADMIN'; const [selected, setSelected] = useState<number | null>(null); const [editShop, setEditShop] = useState(false); const [success, setSuccess] = useState('');
  const [confirm, setConfirm] = useState<{id:number; title:string; patch:Record<string,unknown>; remove?:boolean} | null>(null);
  function action(id:number, title:string, patch:Record<string,unknown>, remove = false) {setSelected(null); setConfirm({id,title,patch,remove});}
  return <State resource={resource}>{data => {
    const title = offers ? 'Offres et paliers' : kind === 'shops' && !admin ? 'Ma boutique' : titles[kind];
    const row = selected === null ? null : data[kind].find(r => r.id === selected);
    return <><Heading title={title} text={offers ? 'Des seuils en unités et des prix dégressifs pour vos produits.' : 'Consultez les informations et gérez les actions disponibles.'} action={kind === 'products' && !admin ? <Link className="button button-primary" to={offers ? '/offres/nouvelle' : '/produits/nouveau'}>{offers ? 'Créer une offre' : 'Ajouter un produit'}</Link> : kind === 'shops' && !admin && isDemo() ? <button className="button-primary" onClick={() => setEditShop(true)}>{data.shops.length ? 'Modifier ma boutique' : 'Créer ma boutique'}</button> : <button disabled={resource.isRefreshing} onClick={resource.refresh}>Actualiser</button>} />
    {success && <p className="success-message" role="status">{success}</p>}
    {data.missing.includes(kind) ? <Notice>Ce parcours nécessite une API de gestion {kind === 'orders' ? 'des commandes professionnelles et de livraison' : kind === 'users' ? 'des utilisateurs' : 'des boutiques'}. Elle n’existe pas dans le backend actuel. Ce parcours peut être essayé dans la démonstration locale depuis la page de connexion.</Notice> : <>
    {kind === 'users' && <DataTable title={title} rows={data.users} search={u => `${u.first_name} ${u.last_name} ${u.phone}`} filters={[{label:'Statut', value:u => u.status}]} columns={[{label:'Utilisateur',render:u => <button className="text-action" onClick={() => setSelected(u.id)}>{u.first_name} {u.last_name}</button>},{label:'Téléphone',render:u => u.phone},{label:'Rôle',secondary:true,render:u => libelleStatut(u.role)},{label:'Statut',render:u => <Badge value={u.status} />}]} />}
    {kind === 'shops' && <DataTable title={title} rows={data.shops} search={s => `${s.name} ${s.location}`} filters={[{label:'Validation',value:s => s.status}]} columns={[{label:'Boutique',render:s => <button className="text-action" onClick={() => setSelected(s.id)}>{s.name}</button>},{label:'Localisation',render:s => s.location},{label:'Validation',render:s => <Badge value={s.status} />},{label:'Produits',secondary:true,render:s => data.products.filter(p => p.merchant_id === s.id).length}]} />}
    {kind === 'products' && <>{data.missing.includes('all-products') && <Notice>Le catalogue API expose uniquement les produits actifs. Les brouillons et la modération administrative restent à raccorder.</Notice>}<DataTable title={title} rows={data.products} search={p => `${p.name} ${p.category}`} filters={[{label:'Catégorie',value:p => p.category},{label:'Statut',value:p => p.status}]} columns={[{label:'Produit',render:p => <><button className="text-action" onClick={() => setSelected(p.id)}>{p.name}</button><small>{p.category || 'Catégorie non fournie'}</small></>},{label:offers ? 'Paliers' : 'Prix individuel',align:'right',render:p => offers ? <>{p.tiers.length} palier(s)<small>Dès {fcfa(p.best_price)}</small></> : fcfa(p.individual_price)},{label:'Stock',secondary:true,render:p => `${p.stock} ${p.unit_label}s`},{label:'Statut',render:p => <Badge value={p.status} />},{label:'Gestion',render:p => !admin ? <Link to={`/offres/${p.id}/paliers`}>{offers ? 'Modifier les paliers' : 'Voir les paliers'}</Link> : <button onClick={() => setSelected(p.id)}>Consulter</button>}]} /></>}
    {kind === 'groups' && <>{data.missing.includes('closed-groups') && <Notice>L’API de liste renvoie uniquement les groupes ouverts. Les groupes clôturés et leur historique restent à raccorder.</Notice>}<GroupTable data={data} /></>}
    {kind === 'orders' && <><Notice>Paiements simulés. Les états de préparation et de livraison de cette démonstration attendent un workflow backend.</Notice><OrderTable data={data} onOpen={setSelected} /></>}
    </>}
    {row && kind === 'orders' && <OrderDetail data={data} id={selected!} close={() => setSelected(null)} refresh={resource.refresh} />}
    {row && kind !== 'orders' && <Panel title={kind === 'users' ? person(data,row.id) : 'name' in row ? row.name : 'Détail'} close={() => setSelected(null)}>
      {kind === 'users' && (() => {const u = data.users.find(u => u.id === selected)!; return <><dl className="details"><dt>Téléphone</dt><dd>{u.phone}</dd><dt>Courriel</dt><dd>{u.email ?? 'Non renseigné'}</dd><dt>Statut</dt><dd><Badge value={u.status} /></dd></dl><button onClick={() => action(u.id, u.status === 'ACTIVE' ? 'Désactiver cet utilisateur' : 'Activer cet utilisateur', {status:u.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'})}>{u.status === 'ACTIVE' ? 'Désactiver' : 'Activer'}</button><h3>Groupes et commandes</h3>{data.orders.filter(o => o.user_id === u.id).map(o => <div className="detail-item" key={o.id}><Link to={`/groupes/${o.group_id}`}>{groupName(data,o.group_id)}</Link><p>KF-{o.id} · {o.quantity} unités · {fcfa(o.total_amount)}</p><p>Transaction simulée {o.transaction_reference} · {libelleStatut(o.payment_status)}</p></div>)}</>;})()}
      {kind === 'shops' && (() => {const s = data.shops.find(s => s.id === selected)!; return <><Badge value={s.status} /><p>{s.description}</p><p>{s.location}</p>{admin && isDemo() && <div className="actions">{s.status === 'PENDING' && <><button onClick={() => action(s.id,'Accepter cette boutique',{status:'APPROVED'})}>Accepter</button><button onClick={() => action(s.id,'Refuser cette boutique',{status:'REJECTED'})}>Refuser</button></>}{s.status === 'APPROVED' && <button className="button-danger" onClick={() => action(s.id,'Suspendre cette boutique',{status:'SUSPENDED'})}>Suspendre</button>}</div>}<h3>Produits et ventes</h3>{data.products.filter(p => p.merchant_id === s.id).map(p => <p key={p.id}>{p.name} · {p.reserved_units} unités réservées · {libelleStatut(p.status)}</p>)}{data.orders.filter(o => o.merchant_id === s.id).slice(0,10).map(o => <p key={o.id}>KF-{o.id} · {fcfa(o.total_amount)} · {libelleStatut(o.order_status)}</p>)}</>;})()}
      {kind === 'products' && (() => {const p = data.products.find(p => p.id === selected)!;return <><Badge value={p.status} /><p>{p.description || 'Description non fournie'}</p>{p.image_url && <img className="product-image" src={p.image_url} alt={p.name} />}<dl className="details"><dt>Prix individuel</dt><dd>{fcfa(p.individual_price)}</dd><dt>Stock / unités réservées</dt><dd>{p.stock} / {isDemo() || !admin ? p.reserved_units : 'Non fourni'}</dd><dt>Localisation</dt><dd>{p.location || 'Non fournie'}</dd><dt>Livraison</dt><dd>{p.delivery_days === null ? 'Non fournie' : `${p.delivery_days} jours`}</dd><dt>Durée de l’offre</dt><dd>{p.duration_days === null ? 'Non fournie' : `${p.duration_days} jours`}</dd></dl><h3>Paliers en unités</h3>{p.tiers.map((t,i) => <p key={t.min_quantity}>{t.min_quantity} {p.tiers[i+1] ? `à ${p.tiers[i+1].min_quantity - 1}` : 'et plus'} : {fcfa(t.unit_price)}</p>)}<div className="actions">{isDemo() && <><Link className="button" to={`/produits/${p.id}/modifier`}>Modifier</Link><button onClick={() => action(p.id, p.status === 'ACTIVE' ? (offers ? 'Clôturer cette offre' : 'Masquer ce produit') : 'Activer ce produit', {status:p.status === 'ACTIVE' ? 'CLOSED' : 'ACTIVE'})}>{p.status === 'ACTIVE' ? (offers ? 'Clôturer' : 'Masquer') : 'Valider / activer'}</button><button className="button-danger" onClick={() => action(p.id,'Supprimer ce produit',{},true)}>Supprimer</button></>}{!admin && <Link className="button" to={`/offres/${p.id}/paliers`}>Modifier les paliers</Link>}</div>{!isDemo() && <Notice>La modification des informations, la suppression et le changement de statut attendent leurs endpoints API.</Notice>}</>;})()}
    </Panel>}
    {confirm && <Confirm title={confirm.title} description="Cette action modifie les données de la démonstration locale. Vérifiez l’élément sélectionné avant de confirmer." close={() => setConfirm(null)} accept={async () => {demoSave(kind,confirm.id,confirm.patch,confirm.remove); setSuccess('Modification enregistrée dans la démonstration.'); resource.refresh();}} />}
    {editShop && <ShopForm shop={data.shops[0]} close={() => setEditShop(false)} saved={() => {setEditShop(false); setSuccess('Informations de la boutique enregistrées.'); resource.refresh();}} />}
    </>;
  }}</State>;
}
function ShopForm({shop,close,saved}: {shop?:Shop;close:()=>void;saved:()=>void}) {const [error,setError]=useState('');return <Panel title={shop ? 'Modifier ma boutique' : 'Créer ma boutique'} close={close}><form onSubmit={e => {e.preventDefault();const f=new FormData(e.currentTarget);try{demoSave('shops',shop?.id ?? null,{name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),location:String(f.get('location')).trim()});saved();}catch(e){setError((e as Error).message);}}}><label className="field">Nom de la boutique<input name="name" required defaultValue={shop?.name} pattern=".*\S.*" /></label><label className="field">Description<textarea name="description" required defaultValue={shop?.description} /></label><label className="field">Localisation<input name="location" required defaultValue={shop?.location} pattern=".*\S.*" /></label><Notice>Une nouvelle boutique est soumise à validation administrative.</Notice>{error && <p role="alert">{error}</p>}<button className="button-primary">Enregistrer</button></form></Panel>;}

export function ManagedGroupPage() {
  const {groupId} = useParams(); const resource = useData(2000); const admin = useSession()?.user.role === 'ADMIN'; const [confirm,setConfirm]=useState(false); const [order,setOrder]=useState<number|null>(null);
  return <State resource={resource}>{data => {
    const g=data.groups.find(g => g.id === Number(groupId));
    if(!g) return <Notice>Ce groupe est introuvable ou n’appartient pas à votre espace.</Notice>;
    return <>
      <Heading title={g.name} text={g.product.name} action={<button onClick={resource.refresh}>Actualiser</button>} />
      <Badge value={g.status} />
      <div className="metrics"><Metric label="Participants" value={g.participants_count} /><Metric label="Unités commandées / objectif" value={`${g.current_quantity} / ${g.target_quantity}`} /><Metric label="Prix actuel par unité" value={fcfa(g.current_unit_price)} /><Metric label="Échéance" value={delai(g.seconds_remaining)} /></div>
      <div className="group-admin-layout">
        <section className="content-block"><h2>Progression de l’achat groupé</h2><progress max={1} value={g.progress_ratio} aria-label="Progression vers l’objectif" /><p>{pourcentage(g.progress_ratio)} % de l’objectif · {g.next_tier ? `Encore ${g.quantity_to_next_tier} unités pour atteindre ${fcfa(g.next_tier.unit_price)} par unité.` : 'Aucun prochain palier disponible.'}</p><dl className="details"><dt>Créateur</dt><dd>{g.creator_id ? person(data,g.creator_id) : 'Non fourni par l’API'}</dd><dt>Montant total des commandes</dt><dd>{g.total_amount === undefined ? "Non fourni par l’API" : fcfa(g.total_amount)}</dd><dt>Objectif minimum</dt><dd>{g.min_quantity} {g.product.unit_label}s</dd><dt>Date limite</dt><dd>{new Date(g.deadline).toLocaleString('fr-FR')}</dd><dt>Économie actuelle / unité</dt><dd>{fcfa(g.unit_saving)}</dd><dt>Économie potentielle / unité au dernier palier</dt><dd>{fcfa(g.potential_unit_saving)}</dd><dt>Économies du groupe au prix actuel</dt><dd>{fcfa(g.group_total_saving)}</dd><dt>Économies réalisées</dt><dd>Non isolées par le backend</dd></dl><Notice>Les seuils reposent sur la quantité totale commandée, distincte du nombre de participants. Tous les membres actifs bénéficient du prix final atteint avant clôture. Si le minimum de {g.min_quantity} unités n’est pas atteint à la date limite, les commandes sont annulées et les paiements remboursés de façon simulée.</Notice>{isDemo() && <p className="muted">Le passage automatique de la date limite n’est pas simulé dans cet adaptateur local.</p>}{admin && isDemo() && g.status === 'OPEN' && <button className="button-danger" onClick={() => setConfirm(true)}>Annuler le groupe</button>}</section>
        <ShareBox groupId={g.id} />
      </div>
      <h2>Commandes individuelles</h2>
      {data.missing.includes('orders') ? <Notice>La consultation des commandes de ce groupe attend une API professionnelle dédiée.</Notice> : <OrderTable data={data} orders={data.orders.filter(o => o.group_id === g.id)} onOpen={setOrder} />}
      {order !== null && <OrderDetail data={data} id={order} close={() => setOrder(null)} refresh={resource.refresh} />}
      {confirm && <Confirm title="Annuler ce groupe" description="Toutes ses commandes seront annulées. Les paiements réussis seront remboursés de façon simulée." close={() => setConfirm(false)} accept={async()=>{demoSave('groups',g.id,{status:'CANCELLED'});resource.refresh();}} />}
    </>;
  }}</State>;
}

export function ProductFormPage({offer=false}: {offer?:boolean}) {
  const {productId}=useParams(); const resource=useData(); return <State resource={resource}>{data=>{const p=data.products.find(p=>p.id===Number(productId)); if(productId&&!p)return <Notice>Produit introuvable dans votre espace.</Notice>; if(productId&&!isDemo())return <Notice>La modification des informations produit nécessite un endpoint supplémentaire.</Notice>; return <ProductForm key={productId ?? 'new'} product={p} offer={offer} />;}}</State>;
}
function ProductForm({product:p,offer}: {product?:ManagedProduct;offer:boolean}) {
  const navigate=useNavigate();const [tiers,setTiers]=useState<EditableTier[]>(p ? tierFromApi(p.tiers) : []);const [price,setPrice]=useState(p?.individual_price ?? 0);const [stock,setStock]=useState(p?.stock ?? 0);const [unit,setUnit]=useState(p?.unit_label ?? 'unité');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const errors=(offer||tiers.length>0)?validateTiers(tiers,stock):[];
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(errors.length)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);const values={name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),unit_label:unit.trim(),individual_price:price,stock,image_url:String(f.get('image_url')||'').trim()||null,tiers:toApiTiers(tiers)};try{if(!values.name||!values.unit_label)throw new Error('Renseignez un nom et une unité de vente.');if(isDemo()){demoSave('products',p?.id??null,{...values,tiers:tiers.map(t=>({min_quantity:t.minQuantity,unit_price:t.unitPrice})),category:String(f.get('category')),location:String(f.get('location')),delivery_days:Number(f.get('delivery_days')),duration_days:Number(f.get('duration_days')),status:p?.status??(tiers.length?'ACTIVE':'DRAFT'),best_price:tiers.at(-1)?.unitPrice??price,groups_count:p?.groups_count??0,reserved_units:p?.reserved_units??0});}else{await createProduct(values);}navigate(offer?'/offres':'/produits');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><Heading title={p?'Modifier le produit':offer?'Créer une offre':'Ajouter un produit'} text="Décrivez le produit, son stock et ses conditions de vente." /><form className="product-form content-block" onSubmit={submit}><div className="form-grid"><label className="field">Nom du produit<input name="name" required pattern=".*\S.*" defaultValue={p?.name}/></label><label className="field">Unité de vente<input required value={unit} onChange={e=>setUnit(e.target.value)}/></label><label className="field">Prix individuel (FCFA)<input type="number" min="1" step="1" required value={price||''} onChange={e=>setPrice(Number(e.target.value))}/></label><label className="field">Stock (unités)<input type="number" min="1" step="1" required value={stock||''} onChange={e=>setStock(Number(e.target.value))}/></label><label className="field field-wide">Description<textarea name="description" defaultValue={p?.description}/></label><label className="field field-wide">Image (URL HTTPS)<input name="image_url" type="url" pattern="https://.*" defaultValue={p?.image_url??''} placeholder="https://…"/></label>{isDemo()?<><label className="field">Catégorie<select name="category" defaultValue={p?.category??'Agriculture'}><option>Agriculture</option><option>Éducation</option><option>Équipement</option></select></label><label className="field">Localisation<input name="location" required defaultValue={p?.location??'Tsévié'}/></label><label className="field">Délai de livraison (jours)<input name="delivery_days" required min="1" step="1" type="number" defaultValue={p?.delivery_days??3}/></label><label className="field">Durée de l’offre (jours)<input name="duration_days" required min="1" step="1" type="number" defaultValue={p?.duration_days??7}/></label></>:<Notice>Catégorie, localisation, délai de livraison et durée de l’offre ne sont pas acceptés par l’API produit actuelle. Ces champs sont disponibles en démonstration.</Notice>}</div>{(offer||p?.tiers.length)?<TierEditor tiers={tiers} onChange={setTiers} stock={stock} retailPrice={price} unitLabel={unit} errors={errors}/>:<Notice>Le produit sera créé en brouillon. Ajoutez ensuite ses paliers depuis les offres pour le publier.</Notice>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="actions"><button className="button-primary" disabled={busy||errors.length>0}>{busy?'Enregistrement…':p?'Enregistrer':offer?'Publier l’offre':'Créer le produit'}</button><Link to={offer?'/offres':'/produits'}>Annuler</Link></div></form></>;
}
export function TierFormPage(){const {productId}=useParams();const resource=useData();return <State resource={resource}>{data=>{const p=data.products.find(p=>p.id===Number(productId));return p?<TierForm key={p.id} product={p}/>:<Notice>Cette offre est introuvable ou ne vous appartient pas.</Notice>;}}</State>;}
function TierForm({product:p}:{product:ManagedProduct}){const navigate=useNavigate();const [tiers,setTiers]=useState(tierFromApi(p.tiers));const [error,setError]=useState('');const [busy,setBusy]=useState(false);const errors=validateTiers(tiers,p.stock);return <><Heading title={`Paliers · ${p.name}`} text={`Prix individuel : ${fcfa(p.individual_price)} · stock : ${p.stock} ${p.unit_label}s.`}/><Notice>Les seuils portent sur les unités commandées. Les intervalles sont continus ; chaque seuil termine l’intervalle précédent.</Notice><TierEditor tiers={tiers} onChange={setTiers} stock={p.stock} retailPrice={p.individual_price} unitLabel={p.unit_label} errors={errors}/>{error&&<p className="form-error" role="alert">{error}</p>}<div className="actions"><button className="button-primary" disabled={busy||errors.length>0} onClick={async()=>{setBusy(true);setError('');try{if(isDemo())demoTiers(p.id,toApiTiers(tiers));else await replaceTiers(p.id,toApiTiers(tiers));navigate('/offres');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Enregistrement…':'Enregistrer les paliers'}</button><Link to="/offres">Annuler</Link></div></>;}
